import { Submission } from '../types';

/**
 * Dados fictícios de demonstração (24 respostas)
 * Utiliza estritamente as categorias oficiais definidas no formulário de Vitória do Xingu.
 * Cada registro é explicitamente marcado com isDemo: true.
 * Todos os comentários seguem a diretriz de futuro, novos investimentos, oportunidades e desenvolvimento.
 */
export const INITIAL_DEMO_SUBMISSIONS: Submission[] = [
  {
    id: 'demo-sub-001',
    moraNoMunicipio: true,
    localidade: 'Sede de Vitória do Xingu',
    localidadeInformada: null,
    prioridade1: 'Saúde',
    prioridade1Outra: null,
    prioridade2: 'Emprego e geração de renda',
    prioridade2Outra: null,
    comentario: 'Continuar avançando no acesso aos serviços de saúde com novos atendimentos especializados.',
    faixaEtaria: '25 a 34 anos',
    status: 'VALID',
    createdAt: '2026-09-13T10:15:00.000Z',
    updatedAt: '2026-09-13T10:15:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-002',
    moraNoMunicipio: true,
    localidade: 'Belo Monte',
    localidadeInformada: null,
    prioridade1: 'Infraestrutura e mobilidade',
    prioridade1Outra: null,
    prioridade2: 'Saúde',
    prioridade2Outra: null,
    comentario: 'Novos investimentos em pavimentação e infraestrutura para valorizar ainda mais nossa região.',
    faixaEtaria: '35 a 44 anos',
    status: 'VALID',
    createdAt: '2026-09-13T10:45:00.000Z',
    updatedAt: '2026-09-13T10:45:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-003',
    moraNoMunicipio: true,
    localidade: 'Agrovila Leonardo da Vinci',
    localidadeInformada: null,
    prioridade1: 'Zona rural e produção',
    prioridade1Outra: null,
    prioridade2: 'Educação e qualificação',
    prioridade2Outra: null,
    comentario: 'Ampliar as oportunidades para quem vive e produz na zona rural com assistência técnica contínua.',
    faixaEtaria: '45 a 59 anos',
    status: 'VALID',
    createdAt: '2026-09-13T11:20:00.000Z',
    updatedAt: '2026-09-13T11:20:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-004',
    moraNoMunicipio: true,
    localidade: 'Sede de Vitória do Xingu',
    localidadeInformada: null,
    prioridade1: 'Emprego e geração de renda',
    prioridade1Outra: null,
    prioridade2: 'Juventude e oportunidades',
    prioridade2Outra: null,
    comentario: 'Mais oportunidades de qualificação profissional para os jovens conquistarem o primeiro emprego.',
    faixaEtaria: '16 a 24 anos',
    status: 'VALID',
    createdAt: '2026-09-13T11:40:00.000Z',
    updatedAt: '2026-09-13T11:40:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-005',
    moraNoMunicipio: true,
    localidade: 'Zona rural / comunidade',
    localidadeInformada: null,
    prioridade1: 'Zona rural e produção',
    prioridade1Outra: null,
    prioridade2: 'Saúde',
    prioridade2Outra: null,
    comentario: 'Fortalecer ainda mais o apoio ao produtor rural e o desenvolvimento da agricultura familiar.',
    faixaEtaria: '45 a 59 anos',
    status: 'VALID',
    createdAt: '2026-09-13T12:05:00.000Z',
    updatedAt: '2026-09-13T12:05:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-006',
    moraNoMunicipio: true,
    localidade: 'Sede de Vitória do Xingu',
    localidadeInformada: null,
    prioridade1: 'Educação e qualificação',
    prioridade1Outra: null,
    prioridade2: 'Infraestrutura e mobilidade',
    prioridade2Outra: null,
    comentario: 'Novos investimentos em tecnologia educacional e valorização contínua do ambiente escolar.',
    faixaEtaria: '25 a 34 anos',
    status: 'VALID',
    createdAt: '2026-09-13T12:30:00.000Z',
    updatedAt: '2026-09-13T12:30:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-007',
    moraNoMunicipio: true,
    localidade: 'Sede de Vitória do Xingu',
    localidadeInformada: null,
    prioridade1: 'Saúde',
    prioridade1Outra: null,
    prioridade2: 'Segurança',
    prioridade2Outra: null,
    comentario: 'Expandir os programas de saúde da família e ações preventivas para todas as idades.',
    faixaEtaria: '35 a 44 anos',
    status: 'VALID',
    createdAt: '2026-09-13T12:55:00.000Z',
    updatedAt: '2026-09-13T12:55:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-008',
    moraNoMunicipio: true,
    localidade: 'Belo Monte',
    localidadeInformada: null,
    prioridade1: 'Emprego e geração de renda',
    prioridade1Outra: null,
    prioridade2: 'Cultura e turismo',
    prioridade2Outra: null,
    comentario: 'Incentivar novos empreendimentos e oportunidades de geração de renda no comércio local.',
    faixaEtaria: '25 a 34 anos',
    status: 'VALID',
    createdAt: '2026-09-13T13:10:00.000Z',
    updatedAt: '2026-09-13T13:10:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-009',
    moraNoMunicipio: true,
    localidade: 'Sede de Vitória do Xingu',
    localidadeInformada: null,
    prioridade1: 'Esporte e lazer',
    prioridade1Outra: null,
    prioridade2: 'Juventude e oportunidades',
    prioridade2Outra: null,
    comentario: 'Apoiar novos projetos esportivos e espaços de lazer para incentivar nossa juventude.',
    faixaEtaria: '16 a 24 anos',
    status: 'VALID',
    createdAt: '2026-09-13T13:30:00.000Z',
    updatedAt: '2026-09-13T13:30:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-010',
    moraNoMunicipio: true,
    localidade: 'Outro local do município',
    localidadeInformada: null,
    prioridade1: 'Saúde',
    prioridade1Outra: null,
    prioridade2: 'Zona rural e produção',
    prioridade2Outra: null,
    comentario: null,
    faixaEtaria: '60 anos ou mais',
    status: 'VALID',
    createdAt: '2026-09-13T13:45:00.000Z',
    updatedAt: '2026-09-13T13:45:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-011',
    moraNoMunicipio: true,
    localidade: 'Agrovila Leonardo da Vinci',
    localidadeInformada: null,
    prioridade1: 'Infraestrutura e mobilidade',
    prioridade1Outra: null,
    prioridade2: 'Saúde',
    prioridade2Outra: null,
    comentario: 'Seguir investindo na infraestrutura urbana e na melhoria contínua dos serviços básicos.',
    faixaEtaria: '35 a 44 anos',
    status: 'VALID',
    createdAt: '2026-09-13T14:00:00.000Z',
    updatedAt: '2026-09-13T14:00:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-012',
    moraNoMunicipio: true,
    localidade: 'Sede de Vitória do Xingu',
    localidadeInformada: null,
    prioridade1: 'Cultura e turismo',
    prioridade1Outra: null,
    prioridade2: 'Emprego e geração de renda',
    prioridade2Outra: null,
    comentario: 'Fortalecer ainda mais o turismo e os eventos culturais que valorizam as belezas do Xingu.',
    faixaEtaria: '25 a 34 anos',
    status: 'VALID',
    createdAt: '2026-09-13T14:15:00.000Z',
    updatedAt: '2026-09-13T14:15:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-013',
    moraNoMunicipio: true,
    localidade: 'Belo Monte',
    localidadeInformada: null,
    prioridade1: 'Saúde',
    prioridade1Outra: null,
    prioridade2: 'Infraestrutura e mobilidade',
    prioridade2Outra: null,
    comentario: 'Ampliar a estrutura de atendimento e o cuidado com a saúde preventiva da população.',
    faixaEtaria: '45 a 59 anos',
    status: 'VALID',
    createdAt: '2026-09-13T14:28:00.000Z',
    updatedAt: '2026-09-13T14:28:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-014',
    moraNoMunicipio: true,
    localidade: 'Sede de Vitória do Xingu',
    localidadeInformada: null,
    prioridade1: 'Emprego e geração de renda',
    prioridade1Outra: null,
    prioridade2: 'Educação e qualificação',
    prioridade2Outra: null,
    comentario: 'Mais oportunidades de capacitação para estimular o empreendedorismo e o comércio.',
    faixaEtaria: '35 a 44 anos',
    status: 'VALID',
    createdAt: '2026-09-13T14:40:00.000Z',
    updatedAt: '2026-09-13T14:40:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-015',
    moraNoMunicipio: true,
    localidade: 'Zona rural / comunidade',
    localidadeInformada: null,
    prioridade1: 'Zona rural e produção',
    prioridade1Outra: null,
    prioridade2: 'Infraestrutura e mobilidade',
    prioridade2Outra: null,
    comentario: 'Avançar nas obras de infraestrutura vicinal para facilitar o escoamento da produção rural.',
    faixaEtaria: '60 anos ou mais',
    status: 'VALID',
    createdAt: '2026-09-13T14:55:00.000Z',
    updatedAt: '2026-09-13T14:55:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-016',
    moraNoMunicipio: true,
    localidade: 'Outro local do município',
    localidadeInformada: null,
    prioridade1: 'Saúde',
    prioridade1Outra: null,
    prioridade2: 'Emprego e geração de renda',
    prioridade2Outra: null,
    comentario: null,
    faixaEtaria: 'Prefiro não informar',
    status: 'VALID',
    createdAt: '2026-09-13T15:05:00.000Z',
    updatedAt: '2026-09-13T15:05:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-017',
    moraNoMunicipio: true,
    localidade: 'Belo Monte',
    localidadeInformada: null,
    prioridade1: 'Educação e qualificação',
    prioridade1Outra: null,
    prioridade2: 'Esporte e lazer',
    prioridade2Outra: null,
    comentario: 'Investir no futuro da juventude integrando educação, esporte e cidadania.',
    faixaEtaria: '25 a 34 anos',
    status: 'VALID',
    createdAt: '2026-09-13T15:15:00.000Z',
    updatedAt: '2026-09-13T15:15:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-018',
    moraNoMunicipio: true,
    localidade: 'Sede de Vitória do Xingu',
    localidadeInformada: null,
    prioridade1: 'Infraestrutura e mobilidade',
    prioridade1Outra: null,
    prioridade2: 'Segurança',
    prioridade2Outra: null,
    comentario: 'Planejar novos investimentos em mobilidade urbana e espaços de convivência comunitária.',
    faixaEtaria: '45 a 59 anos',
    status: 'VALID',
    createdAt: '2026-09-13T15:30:00.000Z',
    updatedAt: '2026-09-13T15:30:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-019',
    moraNoMunicipio: true,
    localidade: 'Agrovila Leonardo da Vinci',
    localidadeInformada: null,
    prioridade1: 'Emprego e geração de renda',
    prioridade1Outra: null,
    prioridade2: 'Zona rural e produção',
    prioridade2Outra: null,
    comentario: 'Fortalecer feiras e iniciativas que valorizem a produção local e gerem mais renda.',
    faixaEtaria: '35 a 44 anos',
    status: 'VALID',
    createdAt: '2026-09-13T15:45:00.000Z',
    updatedAt: '2026-09-13T15:45:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-020',
    moraNoMunicipio: true,
    localidade: 'Sede de Vitória do Xingu',
    localidadeInformada: null,
    prioridade1: 'Saúde',
    prioridade1Outra: null,
    prioridade2: 'Educação e qualificação',
    prioridade2Outra: null,
    comentario: 'Continuar o aprimoramento dos serviços de saúde com foco no bem-estar da terceira idade.',
    faixaEtaria: '60 anos ou mais',
    status: 'VALID',
    createdAt: '2026-09-13T16:00:00.000Z',
    updatedAt: '2026-09-13T16:00:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-021',
    moraNoMunicipio: true,
    localidade: 'Zona rural / comunidade',
    localidadeInformada: null,
    prioridade1: 'Infraestrutura e mobilidade',
    prioridade1Outra: null,
    prioridade2: 'Cultura e turismo',
    prioridade2Outra: null,
    comentario: 'Promover o potencial turístico sustentável e novas parcerias para o desenvolvimento regional.',
    faixaEtaria: '25 a 34 anos',
    status: 'VALID',
    createdAt: '2026-09-13T16:15:00.000Z',
    updatedAt: '2026-09-13T16:15:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-022',
    moraNoMunicipio: true,
    localidade: 'Sede de Vitória do Xingu',
    localidadeInformada: null,
    prioridade1: 'Saúde',
    prioridade1Outra: null,
    prioridade2: 'Juventude e oportunidades',
    prioridade2Outra: null,
    comentario: 'Desenvolver novos programas e oportunidades que acolham os anseios da nossa juventude.',
    faixaEtaria: '16 a 24 anos',
    status: 'VALID',
    createdAt: '2026-09-13T16:30:00.000Z',
    updatedAt: '2026-09-13T16:30:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-023',
    moraNoMunicipio: true,
    localidade: 'Belo Monte',
    localidadeInformada: null,
    prioridade1: 'Emprego e geração de renda',
    prioridade1Outra: null,
    prioridade2: 'Saúde',
    prioridade2Outra: null,
    comentario: null,
    faixaEtaria: '35 a 44 anos',
    status: 'VALID',
    createdAt: '2026-09-13T16:45:00.000Z',
    updatedAt: '2026-09-13T16:45:00.000Z',
    isDemo: true,
  },
  {
    id: 'demo-sub-024',
    moraNoMunicipio: true,
    localidade: 'Agrovila Leonardo da Vinci',
    localidadeInformada: null,
    prioridade1: 'Educação e qualificação',
    prioridade1Outra: null,
    prioridade2: 'Emprego e geração de renda',
    prioridade2Outra: null,
    comentario: 'Expandir parcerias educacionais e cursos de capacitação técnica para o desenvolvimento da cidade.',
    faixaEtaria: '16 a 24 anos',
    status: 'VALID',
    createdAt: '2026-09-13T17:00:00.000Z',
    updatedAt: '2026-09-13T17:00:00.000Z',
    isDemo: true,
  },
];
